DiscosFer/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DiscosFer.Models
{
    public class Cliente
    {
        public Cliente()
        {
            this.Puntuaciones = new HashSet<Puntuacion>();
        }

        [Key]
        public int id { get; set; }
        [Required(ErrorMessage = "Nombre requerido")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "EMail requerido")]
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail is not valid")]
        public string Email { get; set; }

        [DataType(DataType.Date, ErrorMessage = "Fecha nacimiento incorrecta")]
        public Nullable<System.DateTime> FechaNacimiento { get; set; }

        [Required(ErrorMessage = "Fecha de registro requerida")]
        [DataType(DataType.Date, ErrorMessage = "Fecha registro incorrecta")]
        public Nullable<System.DateTime> FechaRegistro { get; set; }

        public virtual ICollection<Puntuacion> Puntuaciones { get; set; }
    }
}

DiscosFer/Models/Disco.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DiscosFer.Models
{
    public class Disco
    {
        public Disco()
        {
            this.Puntuaciones = new HashSet<Puntuacion>();
            //this.DiscoTipos = new HashSet<DiscoTipo>();
        }

        [Key]
        public int IdDisco { get; set; }
        public string Titulo { get; set; }
        public Nullable<double> Agno { get; set; }
        public Nullable<int> IdInterprete { get; set; }

        [ForeignKey("IdInterprete")]
        public virtual Interprete Interprete { get; set; }
        public virtual ICollection<Puntuacion> Puntuaciones { get; set; }
        //public virtual ICollection<DiscoTipo> DiscoTipos { get; set; }
    }
}

DiscosFer/Models/Interprete.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DiscosFer.Models
{
    public class Interprete
    {
        public Interprete()
        {
            this.Discos = new HashSet<Disco>();
        }

        [Key]
        public int IdInterprete { get; set; }

        public string Interprete1 { get; set; }

        public virtual ICollection<Disco> Discos { get; set; }
    }
}

DiscosFer/Models/Puntuacion.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DiscosFer.Models
{
    public class Puntuacion
    {
        [Key]
        public int Id { get; set; }
        public Nullable<int> Idcliente { get; set; }
        public Nullable<int> iddisco { get; set; }
        [Column("Puntuacion")]
        public Nullable<int> PuntuacionVal { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }

        [ForeignKey("Idcliente")]
        public virtual Cliente Cliente { get; set; }

        [ForeignKey("iddisco")]
        public virtual Disco Disco { get; set; }
    }
}

DiscosFer/Controllers/AdminController.cs
using DiscosFer.DataAccessLayer;
using DiscosFer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DiscosFer.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult CreateCustomer()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateCustomer(Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                using (var context = new DiscosDAL())
                {
                    context.Clientes.Add(cliente);
                    context.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            else
                return View();
        }
    }
}

DiscosFer/Controllers/ClientesController.cs
using DiscosFer.DataAccessLayer;
using DiscosFer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DiscosFer.Controllers
{
    public class ClientesController : Controller
    {
        // GET: Clientes
        public ActionResult Index()
        {
            return RedirectToAction("GetClientes");
        }

        public ActionResult GetClientes()
        {
            List<Cliente> clientes;

            using (var context = new DiscosDAL())
            {
                clientes = context.Clientes.ToList();
            }
            return View(clientes);
        }

        public ActionResult GetPuntuaciones(int id)
        {
            List<Puntuacion> puntuaciones;
            using (var context = new DiscosDAL())
            {
                puntuaciones = context.Puntuaciones.Where(p => p.Idcliente == id).ToList();
                return View(puntuaciones);
            }
        }
    }
}

DiscosFer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DiscosFer.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DiscosFer/Views/Admin/CreateCustomer.cshtml
@model DiscosFer.Models.Cliente

@{
    ViewBag.Title = "CreateCustomer";
}

<h2>CreateCustomer</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaNacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaNacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaRegistro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaRegistro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaRegistro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="SaveCustomer" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DiscosFer/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<p>@Html.ActionLink("Ir a clientes", "Index", "Clientes")</p>
<p>@Html.ActionLink("Nuevo cliente", "CreateCustomer")</p>

DiscosFer/Views/Clientes/GetClientes.cshtml
@model IEnumerable<DiscosFer.Models.Cliente>

@{
    ViewBag.Title = "GetClientes";
}

<h2>GetClientes</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaRegistro)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaNacimiento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaRegistro)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.id }) |
            @Html.ActionLink("Puntuaciones", "GetPuntuaciones", new { id=item.id})
        </td>
    </tr>
}

</table>

DiscosFer/Views/Clientes/GetPuntuaciones.cshtml
@model IEnumerable<DiscosFer.Models.Puntuacion>

@{
    ViewBag.Title = "GetPuntuaciones";
}

<h2>GetPuntuaciones</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Idcliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.iddisco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PuntuacionVal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Idcliente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Disco.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PuntuacionVal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

DiscosFer/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DiscosFer/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DiscosFer/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron" style="background-image: url('@Url.Content("~/Content/Images/fiesta_discopeque.jpg")');">
    <h1>DiscoFer</h1>
    <p class="lead">Ford Fairlane Records</p>
    <p><a href="@Url.Action("Index", "Admin")" class="btn btn-primary btn-lg">Admin</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Discos</h2>
        <p>
            <a class="btn btn-default" href="@Url.Action("Index", "Discos")">
                <img src="~/Content/Images/multimedia.png" alt="Discos" width="128" height="128" />
                Ir a discos&raquo;
            </a>
        </p>
    </div>
    <div class="col-md-4">
        <h2>Intérpretes</h2>
        <p>
            <a class="btn btn-default" href="@Url.Action("Index", "Interpretes")">
                <img src="~/Content/Images/music.png" alt="Int&eacute;rpretes" width="128" height="128" />
                Ir a int&eacute;rpretes &raquo;
            </a>
        </p>
    </div>
    <div class="col-md-4">
        <h2>Login</h2>
        <p>
            <a class="btn btn-default" href="@Url.Action("Login", "Login")">
                <img src="~/Content/Images/login.png" alt="Registro" width="128" height="128" />
                Ir a identificaci&oacute;n &raquo;
            </a>
        <p>
            @Html.ActionLink("Acerca de...", "About", null, new { @class = "btn btn-primary" })
        </p>
        </p>
    </div>
</div>

DiscosFer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>